name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install
        working-directory: ./api
        run: npm install
      - name: Build
        working-directory: ./api
        run: npm run build
      - name: Test
        working-directory: ./api
        run: npm test
      - name: Deploy
        working-directory: ./api
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stock-ticker-server"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install
        working-directory: ./client
        run: npm install
      - name: Build
        working-directory: ./client
        run: npm run build
      - name: Test
        working-directory: ./client
        run: npm test
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh_pages
          build_dir: ./client/build
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
