name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install
        working-directory: ./client
        run: npm install
      - name: Build
        working-directory: ./client
        run: npm run build
      - name: Build
        working-directory: ./client
        run: npm test
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh_pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
